### ISSUE TITLE
Prośba o dołączenie do zespołu

### ISSUE THREAD

**Issue by karol-f** [OtwartaPlatformaWyborcza/OPW-client-AngularJS#1]
Witam, zgodnie z README.md otwieram issue aby dołaczyć do zespołu front-endowego.

W czym mogę pomóc:
- AngularJS
- UI, trochę grafika
- REST (w dużo mniejszym stopniu)

Pozdrawiam.

**Comment by adamkowalewski** [comment]
Zaproszenie do Blue Team wysłane.
