### ISSUE TITLE
next page pagination within Obwodowa works when inactive

### ISSUE THREAD

**Issue by adamkowalewski** [OtwartaPlatformaWyborcza/OPW-client-AngularJS#2]
Login, user has only 4 Komisja Obwodowa, pagination bar shows only 1 page, button next still works, 
it is possible to navigate to page 2 when only 1 page was generated

**Comment by marcintokarski** [comment]
Karol,  we must return '#' only for next or prev button. For numbered button we must return url with page number. I fix this bug by use the same condition which you but to hide next or prev button in directive view.

**Comment by karol-f** [comment]
@marcintokarski Thanks for fixing this.
