### ISSUE TITLE
Missing summary field

### ISSUE THREAD

**Issue by adamkowalewski** [OtwartaPlatformaWyborcza/OPW-client-AngularJS#7]
There has to be am input in the bottom of Kandydat list to summarize all votes. 
Label: "Razem" 
Value may be autom. updated. 

Refer to official protocol page 2
http://pkw.gov.pl/g2/oryginal/2015_01/6d4a07c19783328b29a9e28e7be64ba3.pdf

**Comment by marcintokarski** [comment]
fix in 3f58247e3b843ab0302444b7cffc287d6014dfc2
