### ISSUE TITLE
Sortowanie kandydatów 

### ISSUE THREAD

**Issue by adamkowalewski** [OtwartaPlatformaWyborcza/OPW-client-AngularJS#8]
Lista kandydatów musi: 
1. standardowo być posortowana alfabetycznie 
2. nazwisko w samych dużych literach 

[Oficjalna karta do głosowania](http://r-scale-85.dcs.redcdn.pl/scale/o2/tvn/web-content/m/p1/i/42d6c7d61481d1c21bd1635f59edae05/804adad2-ee8f-11e4-b5f8-0025b511226e.png?type=0&srcmode=4&srcx=0/1&srcy=0/1&srcw=640&srch=2000&dstw=640&dsth=2000)

**Comment by karol-f** [comment]
Wymaganie sortowania zostało anulowane przez @adamkowalewski
